name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Collection
      run: |
        newman run ./day1/New Collection.postman_collection.json
        # If you also use environment variables:
        # newman run ./my-collection.postman_collection.json --environment ./my-environment.postman_environment.json
